"""Canonical audio format, fail-loud frames, edge resampling, and tone synthesis.

The lowest layer of the stack: everything backend-agnostic works in the canonical format
defined here. See ADR 0006. Cycle 7 (ADR 0008) adds the DTMF decode + framing seam.
"""

from .dtmf import (
    DEFAULT_DTMF_AMPLITUDE,
    DEFAULT_DTMF_BUFFER_SECONDS,
    DEFAULT_DTMF_CHUNK_BYTES,
    DEFAULT_DTMF_MS,
    DEFAULT_DTMF_TIMEOUT,
    DEFAULT_MULTIMON_BIN,
    DTMF_FREQS,
    MULTIMON_ARGS,
    RADIO_DTMF_BUFFER_SECONDS_ENV_VAR,
    RADIO_DTMF_TIMEOUT_ENV_VAR,
    RADIO_MULTIMON_BIN_ENV_VAR,
    CLEAR,
    BufferedDtmfInput,
    DtmfDecoder,
    DtmfFramer,
    DtmfInput,
    MultimonDtmfDecoder,
    SUBMIT,
    dtmf_window_bytes,
    load_dtmf_buffer_seconds,
    load_dtmf_timeout,
    load_multimon_bin,
    synth_dtmf,
)
from .format import (
    CANONICAL_CHANNELS,
    CANONICAL_FORMAT,
    CANONICAL_RATE,
    CANONICAL_WIDTH,
    AudioFormat,
    AudioFormatMismatch,
    AudioFrame,
)
from .resample import MULTIMON_RATE, resample, to_canonical, to_multimon
from .tone import DEFAULT_RAMP_MS, synth_tone

__all__ = [
    "AudioFormat",
    "AudioFormatMismatch",
    "AudioFrame",
    "CANONICAL_CHANNELS",
    "CANONICAL_FORMAT",
    "CANONICAL_RATE",
    "CANONICAL_WIDTH",
    "BufferedDtmfInput",
    "CLEAR",
    "DEFAULT_DTMF_AMPLITUDE",
    "DEFAULT_DTMF_BUFFER_SECONDS",
    "DEFAULT_DTMF_CHUNK_BYTES",
    "DEFAULT_DTMF_MS",
    "DEFAULT_DTMF_TIMEOUT",
    "DEFAULT_MULTIMON_BIN",
    "DEFAULT_RAMP_MS",
    "DTMF_FREQS",
    "DtmfDecoder",
    "DtmfFramer",
    "DtmfInput",
    "MULTIMON_ARGS",
    "MULTIMON_RATE",
    "MultimonDtmfDecoder",
    "RADIO_DTMF_BUFFER_SECONDS_ENV_VAR",
    "RADIO_DTMF_TIMEOUT_ENV_VAR",
    "RADIO_MULTIMON_BIN_ENV_VAR",
    "SUBMIT",
    "dtmf_window_bytes",
    "load_dtmf_buffer_seconds",
    "load_dtmf_timeout",
    "load_multimon_bin",
    "resample",
    "synth_dtmf",
    "synth_tone",
    "to_canonical",
    "to_multimon",
]
