"""DTMF command dispatch and voice services.

Backend-agnostic, like the auth layer: services operate on the sound-card audio surface
(`transmit`/`receive`), so every service works identically in both radio modes. A
`Dispatcher` plugs into `AuthGate`'s command hook; registered services produce audio the
dispatcher transmits.
"""

from .dispatch import (
    DispatchResult,
    Dispatcher,
    Service,
    ServiceContext,
    ServiceRegistry,
)
from .cw import (
    DEFAULT_CW_TONE_HZ,
    DEFAULT_CW_WPM,
    RADIO_CW_TONE_HZ_ENV_VAR,
    RADIO_CW_WPM_ENV_VAR,
    CwId,
    cw_timeline,
    load_cw_tone_hz,
    load_cw_wpm,
    unit_ms,
)
from .station_id import (
    DEFAULT_ID_INTERVAL,
    MAX_ID_INTERVAL,
    RADIO_CALLSIGN_ENV_VAR,
    RADIO_ID_INTERVAL_ENV_VAR,
    IdEncoder,
    StationId,
    StubId,
    load_callsign,
    load_id_interval,
)
from .fetch import (
    DEFAULT_FETCH_TIMEOUT,
    FetchError,
    Fetcher,
    StubFetcher,
    UrllibFetcher,
)
from .time_service import (
    RADIO_TZ_ENV_VAR,
    TIME_DIGIT,
    TIME_NAME,
    format_spoken_time,
    load_timezone,
    register,
    time_service,
)
from .weather_service import (
    WEATHER_DIGIT,
    WEATHER_NAME,
    format_spoken_weather,
    load_weather_base_url,
    load_weather_timeout,
    weather_service,
)
from .astro_service import (
    ASTRO_DIGIT,
    ASTRO_NAME,
    astro_service,
    format_spoken_astro,
)
from .quote_service import (
    QUOTE_DIGIT,
    QUOTE_NAME,
    format_spoken_quote,
    load_quote_base_url,
    quote_service,
)
from .battery_service import (
    BATTERY_DIGIT,
    BATTERY_NAME,
    battery_service,
    format_spoken_battery,
    load_battery_base_url,
)
from .bible_service import (
    BIBLE_DIGIT,
    BIBLE_NAME,
    bible_service,
    format_spoken_bible,
    load_bible_base_url,
    load_bible_translation,
)
from .tts import (
    RADIO_TTS_VOICE_ENV_VAR,
    PiperTts,
    StubTts,
    TtsEngine,
    load_tts_voice,
)
from .voice_id import (
    DEFAULT_ID_MODE,
    ID_MODES,
    PHONETIC,
    RADIO_ID_MODE_ENV_VAR,
    VoiceId,
    build_id_encoder,
    load_id_mode,
    spell_callsign,
)

__all__ = [
    "ASTRO_DIGIT",
    "ASTRO_NAME",
    "BATTERY_DIGIT",
    "BATTERY_NAME",
    "BIBLE_DIGIT",
    "BIBLE_NAME",
    "QUOTE_DIGIT",
    "QUOTE_NAME",
    "battery_service",
    "bible_service",
    "format_spoken_battery",
    "format_spoken_bible",
    "format_spoken_quote",
    "load_battery_base_url",
    "load_bible_base_url",
    "load_bible_translation",
    "load_quote_base_url",
    "quote_service",
    "DispatchResult",
    "Dispatcher",
    "DEFAULT_CW_TONE_HZ",
    "DEFAULT_CW_WPM",
    "DEFAULT_FETCH_TIMEOUT",
    "FetchError",
    "Fetcher",
    "StubFetcher",
    "UrllibFetcher",
    "WEATHER_DIGIT",
    "WEATHER_NAME",
    "astro_service",
    "format_spoken_astro",
    "format_spoken_weather",
    "load_weather_base_url",
    "load_weather_timeout",
    "weather_service",
    "DEFAULT_ID_INTERVAL",
    "DEFAULT_ID_MODE",
    "ID_MODES",
    "MAX_ID_INTERVAL",
    "PHONETIC",
    "RADIO_CALLSIGN_ENV_VAR",
    "RADIO_CW_TONE_HZ_ENV_VAR",
    "RADIO_CW_WPM_ENV_VAR",
    "RADIO_ID_INTERVAL_ENV_VAR",
    "RADIO_ID_MODE_ENV_VAR",
    "RADIO_TTS_VOICE_ENV_VAR",
    "RADIO_TZ_ENV_VAR",
    "CwId",
    "IdEncoder",
    "PiperTts",
    "Service",
    "ServiceContext",
    "ServiceRegistry",
    "StationId",
    "StubId",
    "StubTts",
    "TIME_DIGIT",
    "TIME_NAME",
    "TtsEngine",
    "VoiceId",
    "build_id_encoder",
    "cw_timeline",
    "format_spoken_time",
    "load_callsign",
    "load_cw_tone_hz",
    "load_cw_wpm",
    "load_id_interval",
    "load_id_mode",
    "load_timezone",
    "load_tts_voice",
    "register",
    "spell_callsign",
    "time_service",
    "unit_ms",
]
